"""initial smart inventory schema"""
from alembic import op
import sqlalchemy as sa
revision="0001_initial";down_revision=None;branch_labels=None;depends_on=None

def upgrade():
    op.create_table('users',
        sa.Column('id',sa.Integer(),primary_key=True),sa.Column('username',sa.String(100),nullable=False,unique=True),sa.Column('email',sa.String(150),nullable=False,unique=True),sa.Column('password_hash',sa.String(255),nullable=False),sa.Column('role',sa.String(30),nullable=False),sa.Column('is_active',sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column('warehouse_id',sa.Integer(),nullable=True),sa.Column('created_at',sa.DateTime(),nullable=False),sa.Column('updated_at',sa.DateTime(),nullable=False),sa.Column('created_by',sa.Integer(),nullable=True))
    op.create_table('warehouses',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('warehouse_code',sa.String(50),nullable=False,unique=True),sa.Column('name',sa.String(150),nullable=False),sa.Column('city',sa.String(100),nullable=False),sa.Column('address',sa.Text(),nullable=False),sa.Column('capacity',sa.Integer(),nullable=False),sa.Column('manager_id',sa.Integer(),nullable=True),sa.Column('is_active',sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column('created_at',sa.DateTime(),nullable=False),sa.Column('updated_at',sa.DateTime(),nullable=False),sa.Column('created_by',sa.Integer(),nullable=True))
    op.create_foreign_key('fk_users_warehouse','users','warehouses',['warehouse_id'],['id'])
    op.create_foreign_key('fk_users_created_by','users','users',['created_by'],['id'])
    op.create_foreign_key('fk_warehouses_manager','warehouses','users',['manager_id'],['id'])
    op.create_foreign_key('fk_warehouses_created_by','warehouses','users',['created_by'],['id'])
    simple=[
    ('categories',[('name',sa.String(100),{'unique':True}),('is_active',sa.Boolean(),{'server_default':sa.true()})],None),
    ('suppliers',[('supplier_code',sa.String(50),{'unique':True}),('name',sa.String(150),{}),('email',sa.String(150),{'unique':True}),('phone',sa.String(10),{}),('gst_number',sa.String(15),{}),('address',sa.Text(),{}),('lead_time_days',sa.Integer(),{'server_default':'0'}),('is_active',sa.Boolean(),{'server_default':sa.true()})],None),
    ('customers',[('customer_code',sa.String(50),{'unique':True}),('name',sa.String(150),{}),('email',sa.String(150),{'unique':True}),('phone',sa.String(10),{}),('address',sa.Text(),{}),('credit_limit',sa.Numeric(14,2),{'server_default':'0'}),('is_active',sa.Boolean(),{'server_default':sa.true()})],None),
    ]
    for name,cols,_ in simple:
        op.create_table(name,sa.Column('id',sa.Integer(),primary_key=True),* [sa.Column(n,t,nullable=False,**kw) for n,t,kw in cols],sa.Column('created_at',sa.DateTime(),nullable=False),sa.Column('updated_at',sa.DateTime(),nullable=False),sa.Column('created_by',sa.Integer(),nullable=True),sa.ForeignKeyConstraint(['created_by'],['users.id']))
    op.create_table('products',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('name',sa.String(150),nullable=False),sa.Column('sku',sa.String(80),nullable=False,unique=True),sa.Column('barcode',sa.String(80),unique=True),sa.Column('category_id',sa.Integer(),nullable=False),sa.Column('unit',sa.String(20),nullable=False),sa.Column('cost_price',sa.Numeric(12,2),nullable=False),sa.Column('selling_price',sa.Numeric(12,2),nullable=False),sa.Column('reorder_level',sa.Integer(),nullable=False),sa.Column('reorder_quantity',sa.Integer(),nullable=False),sa.Column('preferred_supplier_id',sa.Integer()),sa.Column('is_active',sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column('created_at',sa.DateTime(),nullable=False),sa.Column('updated_at',sa.DateTime(),nullable=False),sa.Column('created_by',sa.Integer()),sa.ForeignKeyConstraint(['category_id'],['categories.id']),sa.ForeignKeyConstraint(['preferred_supplier_id'],['suppliers.id']),sa.ForeignKeyConstraint(['created_by'],['users.id']))
    op.create_table('inventory',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('product_id',sa.Integer(),nullable=False),sa.Column('warehouse_id',sa.Integer(),nullable=False),sa.Column('quantity_on_hand',sa.Integer(),nullable=False,server_default='0'),sa.Column('quantity_reserved',sa.Integer(),nullable=False,server_default='0'),sa.Column('created_at',sa.DateTime(),nullable=False),sa.Column('updated_at',sa.DateTime(),nullable=False),sa.Column('created_by',sa.Integer()),sa.ForeignKeyConstraint(['product_id'],['products.id']),sa.ForeignKeyConstraint(['warehouse_id'],['warehouses.id']),sa.ForeignKeyConstraint(['created_by'],['users.id']),sa.UniqueConstraint('product_id','warehouse_id',name='uq_inventory_product_warehouse'))
    op.create_table('purchase_orders',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('po_number',sa.String(60),nullable=False,unique=True),sa.Column('supplier_id',sa.Integer(),nullable=False),sa.Column('warehouse_id',sa.Integer(),nullable=False),sa.Column('expected_delivery_date',sa.Date(),nullable=False),sa.Column('received_at',sa.DateTime()),sa.Column('total_amount',sa.Numeric(14,2),nullable=False,server_default='0'),sa.Column('status',sa.String(30),nullable=False),sa.Column('created_at',sa.DateTime(),nullable=False),sa.Column('updated_at',sa.DateTime(),nullable=False),sa.Column('created_by',sa.Integer()),sa.ForeignKeyConstraint(['supplier_id'],['suppliers.id']),sa.ForeignKeyConstraint(['warehouse_id'],['warehouses.id']),sa.ForeignKeyConstraint(['created_by'],['users.id']))
    op.create_table('purchase_order_items',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('purchase_order_id',sa.Integer(),nullable=False),sa.Column('product_id',sa.Integer(),nullable=False),sa.Column('quantity_ordered',sa.Integer(),nullable=False),sa.Column('quantity_received',sa.Integer(),nullable=False,server_default='0'),sa.Column('unit_cost',sa.Numeric(12,2),nullable=False),sa.ForeignKeyConstraint(['purchase_order_id'],['purchase_orders.id']),sa.ForeignKeyConstraint(['product_id'],['products.id']))
    op.create_table('sales_orders',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('so_number',sa.String(60),nullable=False,unique=True),sa.Column('customer_id',sa.Integer(),nullable=False),sa.Column('warehouse_id',sa.Integer(),nullable=False),sa.Column('subtotal',sa.Numeric(14,2),nullable=False,server_default='0'),sa.Column('tax_amount',sa.Numeric(14,2),nullable=False,server_default='0'),sa.Column('grand_total',sa.Numeric(14,2),nullable=False,server_default='0'),sa.Column('status',sa.String(30),nullable=False),sa.Column('courier_name',sa.String(100)),sa.Column('tracking_number',sa.String(100),unique=True),sa.Column('dispatched_at',sa.DateTime()),sa.Column('delivered_at',sa.DateTime()),sa.Column('created_at',sa.DateTime(),nullable=False),sa.Column('updated_at',sa.DateTime(),nullable=False),sa.Column('created_by',sa.Integer()),sa.ForeignKeyConstraint(['customer_id'],['customers.id']),sa.ForeignKeyConstraint(['warehouse_id'],['warehouses.id']),sa.ForeignKeyConstraint(['created_by'],['users.id']))
    op.create_table('sales_order_items',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('sales_order_id',sa.Integer(),nullable=False),sa.Column('product_id',sa.Integer(),nullable=False),sa.Column('quantity',sa.Integer(),nullable=False),sa.Column('unit_price',sa.Numeric(12,2),nullable=False),sa.Column('line_total',sa.Numeric(14,2),nullable=False),sa.ForeignKeyConstraint(['sales_order_id'],['sales_orders.id']),sa.ForeignKeyConstraint(['product_id'],['products.id']))
    op.create_table('stock_movements',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('product_id',sa.Integer(),nullable=False),sa.Column('warehouse_id',sa.Integer(),nullable=False),sa.Column('movement_type',sa.String(40),nullable=False),sa.Column('quantity',sa.Integer(),nullable=False),sa.Column('reference_id',sa.Integer()),sa.Column('balance_after',sa.Integer(),nullable=False),sa.Column('performed_by',sa.Integer(),nullable=False),sa.Column('created_at',sa.DateTime(),nullable=False),sa.Column('updated_at',sa.DateTime(),nullable=False),sa.Column('created_by',sa.Integer()),sa.ForeignKeyConstraint(['product_id'],['products.id']),sa.ForeignKeyConstraint(['warehouse_id'],['warehouses.id']),sa.ForeignKeyConstraint(['performed_by'],['users.id']),sa.ForeignKeyConstraint(['created_by'],['users.id']))
    op.create_table('returns',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('so_id',sa.Integer(),nullable=False),sa.Column('reason',sa.Text(),nullable=False),sa.Column('status',sa.String(20),nullable=False),sa.Column('refund_amount',sa.Numeric(14,2),nullable=False,server_default='0'),sa.Column('rejection_reason',sa.Text()),sa.Column('inspected_by',sa.Integer()),sa.Column('created_at',sa.DateTime(),nullable=False),sa.Column('updated_at',sa.DateTime(),nullable=False),sa.Column('created_by',sa.Integer()),sa.ForeignKeyConstraint(['so_id'],['sales_orders.id']),sa.ForeignKeyConstraint(['inspected_by'],['users.id']),sa.ForeignKeyConstraint(['created_by'],['users.id']))
    op.create_table('return_items',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('return_id',sa.Integer(),nullable=False),sa.Column('product_id',sa.Integer(),nullable=False),sa.Column('quantity',sa.Integer(),nullable=False),sa.Column('condition',sa.String(20)),sa.ForeignKeyConstraint(['return_id'],['returns.id']),sa.ForeignKeyConstraint(['product_id'],['products.id']))
    op.create_table('audit_logs',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('user_id',sa.Integer(),nullable=False),sa.Column('action',sa.String(30),nullable=False),sa.Column('entity_type',sa.String(50),nullable=False),sa.Column('entity_id',sa.Integer(),nullable=False),sa.Column('old_value',sa.Text()),sa.Column('new_value',sa.Text()),sa.Column('timestamp',sa.DateTime(),nullable=False),sa.ForeignKeyConstraint(['user_id'],['users.id']))
    op.create_table('transfers',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('product_id',sa.Integer(),nullable=False),sa.Column('source_warehouse_id',sa.Integer(),nullable=False),sa.Column('destination_warehouse_id',sa.Integer(),nullable=False),sa.Column('quantity',sa.Integer(),nullable=False),sa.Column('quantity_received',sa.Integer(),nullable=False,server_default='0'),sa.Column('status',sa.String(20),nullable=False),sa.Column('shortage',sa.Integer(),nullable=False,server_default='0'),sa.Column('created_at',sa.DateTime(),nullable=False),sa.Column('updated_at',sa.DateTime(),nullable=False),sa.Column('created_by',sa.Integer()),sa.ForeignKeyConstraint(['product_id'],['products.id']),sa.ForeignKeyConstraint(['source_warehouse_id'],['warehouses.id']),sa.ForeignKeyConstraint(['destination_warehouse_id'],['warehouses.id']),sa.ForeignKeyConstraint(['created_by'],['users.id']))
    op.create_table('adjustments',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('product_id',sa.Integer(),nullable=False),sa.Column('warehouse_id',sa.Integer(),nullable=False),sa.Column('quantity',sa.Integer(),nullable=False),sa.Column('reason',sa.String(30),nullable=False),sa.Column('status',sa.String(20),nullable=False),sa.Column('created_by',sa.Integer(),nullable=False),sa.Column('approved_by',sa.Integer()),sa.Column('created_at',sa.DateTime(),nullable=False),sa.Column('updated_at',sa.DateTime(),nullable=False),sa.ForeignKeyConstraint(['product_id'],['products.id']),sa.ForeignKeyConstraint(['warehouse_id'],['warehouses.id']),sa.ForeignKeyConstraint(['created_by'],['users.id']),sa.ForeignKeyConstraint(['approved_by'],['users.id']))

def downgrade():
    for t in ['adjustments','transfers','audit_logs','return_items','returns','stock_movements','sales_order_items','sales_orders','purchase_order_items','purchase_orders','inventory','products','customers','suppliers','categories']:
        op.drop_table(t)
    op.drop_constraint('fk_warehouses_created_by','warehouses',type_='foreignkey');op.drop_constraint('fk_warehouses_manager','warehouses',type_='foreignkey');op.drop_table('warehouses')
    op.drop_constraint('fk_users_created_by','users',type_='foreignkey');op.drop_constraint('fk_users_warehouse','users',type_='foreignkey');op.drop_table('users')
